# ## Exercise 4: Request Processing System (Producer-Consumer)
# 4. Implement a simulation of a request processing system. Requests are generated by a dispatcher thread, stored in a shared queue, and processed by a worker thread. The queue must store, at most, N requests.
#    a. Implement a solution using semaphores and mutexes.
#    b. Implement a solution using an adapted monitor. Although there is no `Monitor` type in Python's standard library, the `threading.Condition` class, used in association with an instance of `threading.Lock()`, allows an equivalent implementation.

# ---

import threading
import monitor
import time


N = 10

running = True

monitor1 = monitor.MonitorBuffer(N)

def dispatcher():
    global queue
    i = 0
    while running:   
        i+=1
        monitor1.inserir(i)


def consumer():
    global queue

    while running:
        monitor1.remover()

c = threading.Thread(target=consumer)
d = threading.Thread(target=dispatcher)

c.start()
d.start()

time.sleep(3)

running = False

c.join()
d.join()