# ## Exercise 4: Request Processing System (Producer-Consumer)
# 4. Implement a simulation of a request processing system. Requests are generated by a dispatcher thread, stored in a shared queue, and processed by a worker thread. The queue must store, at most, N requests.
#    a. Implement a solution using semaphores and mutexes.
#    b. Implement a solution using an adapted monitor. Although there is no `Monitor` type in Python's standard library, the `threading.Condition` class, used in association with an instance of `threading.Lock()`, allows an equivalent implementation.
#    c. Modify the simulation for multiple worker threads.

# ---